module.exports = {
  TYPE_OBJECT: "object",
  TYPE_STRING: "string",

  JWE_ALGORITHM: "RSA-OAEP-256",
  JWS_ALGORITHM: "RS256",
  DIGEST_ALGORITHM: "SHA-256",

  JWE_ENCRYPTION_METHOD: "A128CBC-HS256",

  TOKEN_EXPIRY_TIME_IN_MILLISECONDS: 300000, // 5 mins
};
